# References: 
# - https://github.com/rstudio/pins-python/tree/main/docs
# - https://github.com/machow/quartodoc/blob/main/docs/_quarto.yml
# - https://github.com/quarto-dev/quarto-web/blob/main/_quarto.yml
# Key Commands:
#   - cd docs
#   - quartodoc build
#   - quarto preview
#   - quarto publish gh-pages

project:
  type: website
  output-dir: _site

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

website:
  title: "timetk for Python"
  description: "Your toolkit for time series in Python."
  favicon: "favicon.ico"
  google-analytics: "330861489"
  open-graph: true
  twitter-card: true
  site-url: https://business-science.github.io/pytimetk/
  repo-url: https://github.com/business-science/pytimetk
  issue-url: https://github.com/business-science/pytimetk/issues
  repo-actions: [edit, issue]
  page-navigation: true
  search: true
  navbar:
    background: primary
    pinned: true
    logo: "logo-timetk.png"
    collapse-below: lg
    left:
      - text: Tutorials
        file: guides/index.qmd
      - text: Docs
        file: reference/index.qmd
    tools:
      - icon: github
        href: https://github.com/business-science/pytimetk


format:
  html:
    toc: true
    theme: 
      light: [lux, theme-light.scss, theme.scss]
      dark: [lux, theme-dark.scss, theme.scss]
    highlight-style: github
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px


quartodoc:
  package: timetk
  sidebar: _sidebar.yml
  sections:
    - title: 🐼 Pandas Extensions
      desc: Time series functions that manipulate DataFrames.
      package: timetk.summarize_by_time
      contents:
        - summarize_by_time
    - title: 💾 Datasets
      package: timetk.datasets.get_datasets
      desc: Try out `timetk` on some of our datasets.
      contents:
        - load_dataset
        - get_available_datasets
