# References: 
# - https://github.com/rstudio/pins-python/tree/main/docs
# - https://github.com/machow/quartodoc/blob/main/docs/_quarto.yml
# - https://github.com/quarto-dev/quarto-web/blob/main/_quarto.yml
# - https://nixtla.github.io/statsforecast/
# - https://github.com/nixtla/statsforecast
# - 
# Key Commands:
#   - cd docs
#   - quartodoc build
#   - quarto preview
#   - quarto publish gh-pages

project:
  type: website
  output-dir: _site

execute:
  freeze: auto  # re-render only when source changes

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

website:
  title: "pytimetk"
  description: "Your toolkit for time series in Python."
  favicon: "favicon.ico"
  google-analytics: "330861489"
  open-graph: true
  twitter-card: true
  site-url: https://business-science.github.io/pytimetk/
  repo-url: https://github.com/business-science/pytimetk
  issue-url: https://github.com/business-science/pytimetk/issues
  repo-actions: [edit, issue]
  page-navigation: true
  search: true
  navbar:
    background: primary
    pinned: true
    logo: "https://www.business-science.io/img/business-science-logo.png"
    # logo: "logo-timetk.png"
    collapse-below: lg
    # left:
      # - text: Tutorials
      #   file: guides/index.qmd
      # - text: Docs
      #   file: reference/index.qmd
    tools:
      - icon: github
        href: https://github.com/business-science/pytimetk
  sidebar: 
    collapse-level: 1
    contents: 
      - text: "PyTimeTK 📈"
        file: index.qmd
      - text: "---"
      - section: "🏁 Getting Started:"
        contents: getting-started/*
      - section: "🗺️ Guides:"
        contents: guides/*
      - section: "📘 Applied Tutorials:"
        contents: tutorials/*
      - text: "---"
      - text: 📄 API Reference
        file: reference/index.qmd
      - text: "---"
      - text: ⭐ PyTimeTK on Github
        file: https://github.com/business-science/pytimetk
        external: true
      - text: "---"
      - text: 🍻 Contributing
        file: contributing.qmd
      - text: "---"
      - section: "📚 More References:"
      - text: Business Science
        file: https://www.business-science.io/index.html
        external: true
      - text: Quant Science
        file: https://www.quantscience.io/
        external: true
      - text: Timetk (R Version)
        file: https://business-science.github.io/timetk/
        external: true


format:
  html:
    toc: true
    theme: 
      light: [lux, theme-light.scss, theme.scss]
      dark: [lux, theme-dark.scss, theme.scss]
    highlight-style: github
    linestretch: 1.8
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px


quartodoc:
  package: pytimetk
  sidebar: _sidebar.yml
  sections:
    - title: 🚀 Data Visualization
      desc: Visualize time series data with one line of code.
      package: pytimetk
      contents:
      - plot_timeseries
    - title: 🔥 Wrangling Pandas Time Series DataFrames
      desc: Bend time series data to your will.
      package: pytimetk
      contents:
        - summarize_by_time
        - pad_by_time
        - future_frame
    - title: 🏗️ Adding Features to Time Series DataFrames (Augmenting)
      desc: Add one or more feature columns to time series data.
      package: pytimetk
      contents:
        - augment_timeseries_signature
        - augment_holiday_signature
        - augment_lags
        - augment_leads
        - augment_rolling
        - augment_expanding
    - title: TS Features
      desc: Python implementation of the R package `tsfeatures`.
      package: pytimetk
      contents:
        - ts_features
        - ts_summary
    - title: 🐼 Time Series for Pandas Series
      desc: Time series functions that generate / manipulate Pandas Series.
      package: pytimetk
      contents:        
        - make_future_timeseries
        - make_weekday_sequence
        - make_weekend_sequence
        - get_date_summary
        - get_frequency_summary
        - get_diff_summary
        - get_frequency
        - get_timeseries_signature
        - get_holiday_signature 
    - title: 🛠️ Date Utilities
      desc: Helper functions to make your life easier.
      package: pytimetk
      contents:    
        - floor_date
        - is_holiday
        - week_of_month
        - timeseries_unit_frequency_table
    - title: 🛠️ Visualization Utilities
      desc: Helper functions to make your life easier.
      package: pytimetk
      contents:    
        - theme_timetk
        - palette_timetk
    - title: Extra Pandas Helpers (That Help Beyond Just Time Series)
      package: pytimetk
      contents:
      - glimpse
      - flatten_multiindex_column_names
    - title: 💾 12 Datasets
      package: pytimetk.datasets.get_datasets
      desc: Practice `pytimetk` with 12 complementary time series datasets.
      contents:
        - get_available_datasets
        - load_dataset
        
