name: timetk-checks

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.python-version }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, python-version: '3.9' }
          - { os: ubuntu-latest, python-version: '3.10' }
          - { os: ubuntu-latest, python-version: '3.11' }
          - { os: windows-latest, python-version: '3.9' }
          - { os: macos-latest, python-version: '3.9' }

    steps:
      - name: Set up Python Version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.python-version }}}

      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install package
        run: poetry install

      - name: Test with pytest
        run: poetry run pytest tests/ --verbose